apiVersion: v2
name: marmot
description: Marmot is an open-source data catalog that helps teams discover, understand, and govern their data assets. It's designed for modern data ecosystems where data flows through multiple systems, formats, and teams.
type: application
version: 0.6.1
appVersion: "0.6.0"
home: https://github.com/marmotdata/marmot
sources:
  - https://github.com/marmotdata/marmot
maintainers:
  - name: Charlie Haley
    email: charlie@marmotdata.io
keywords:
  - marmot
  - data
  - data catalog
  - lineage
  - catalog
  - data discovery
  - data governance
  - metadata
  - data lineage
  - observability
  - openlineage
  - kubernetes
  - postgresql

dependencies:
  - name: postgresql
    version: "16.7.8"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
